<?php

return [
    'formats_pdf_path' => env('CSEE_FORMATS_PDF_PATH', base_path('CSEE_FORMATS_2022.pdf')),
    'formats_pdf_filename' => env('CSEE_FORMATS_PDF_FILENAME', 'csee_formats_2022.pdf'),

    'official_links' => [
        'results_directory' => 'https://www.necta.go.tz/results/view/csee',
        'results_2025' => 'https://onlinesys.necta.go.tz/results/2025/csee/index.htm',
        'publications' => 'https://www.necta.go.tz/publications/all',
    ],

    'official_subjects' => [
        ['code' => '010', 'name' => 'QUALIFYING TEST', 'category' => 'BUSINESS', 'subject_group_label' => 'Qualifying Test', 'written_papers' => 1, 'source_page' => 1],
        ['code' => '011', 'name' => 'CIVICS', 'category' => 'ARTS', 'subject_group_label' => 'Core Subjects', 'written_papers' => 1, 'source_page' => 14],
        ['code' => '012', 'name' => 'HISTORY', 'category' => 'ARTS', 'subject_group_label' => 'Core Subjects', 'written_papers' => 1, 'source_page' => 18],
        ['code' => '013', 'name' => 'GEOGRAPHY', 'category' => 'ARTS', 'subject_group_label' => 'Core Subjects', 'written_papers' => 1, 'source_page' => 22],
        ['code' => '014', 'name' => 'BIBLE KNOWLEDGE', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 27],
        ['code' => '015', 'name' => 'ELIMU YA DINI YA KIISLAMU', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 31],
        ['code' => '016', 'name' => 'FINE ART', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 2, 'source_page' => 35],
        ['code' => '017', 'name' => 'MUSIC', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 2, 'source_page' => 39],
        ['code' => '018', 'name' => 'PHYSICAL EDUCATION', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 42],
        ['code' => '019', 'name' => 'THEATRE ARTS', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 45],
        ['code' => '021', 'name' => 'KISWAHILI', 'category' => 'ARTS', 'subject_group_label' => 'Core Subjects', 'written_papers' => 1, 'source_page' => 48],
        ['code' => '022', 'name' => 'ENGLISH LANGUAGE', 'category' => 'ARTS', 'subject_group_label' => 'Core Subjects', 'written_papers' => 1, 'source_page' => 51],
        ['code' => '023', 'name' => 'FRENCH LANGUAGE', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 55],
        ['code' => '024', 'name' => 'LITERATURE IN ENGLISH', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 58],
        ['code' => '025', 'name' => 'ARABIC LANGUAGE', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 61],
        ['code' => '026', 'name' => 'CHINESE LANGUAGE', 'category' => 'ARTS', 'subject_group_label' => 'Optional Subjects', 'written_papers' => 1, 'source_page' => 66],
        ['code' => '031', 'name' => 'PHYSICS', 'category' => 'SCIENCE', 'subject_group_label' => 'Natural Sciences', 'written_papers' => 2, 'source_page' => 69],
        ['code' => '032', 'name' => 'CHEMISTRY', 'category' => 'SCIENCE', 'subject_group_label' => 'Natural Sciences', 'written_papers' => 2, 'source_page' => 75],
        ['code' => '033', 'name' => 'BIOLOGY', 'category' => 'SCIENCE', 'subject_group_label' => 'Core Subjects', 'written_papers' => 2, 'source_page' => 80],
        ['code' => '034', 'name' => 'AGRICULTURE', 'category' => 'SCIENCE', 'subject_group_label' => 'Natural Sciences', 'written_papers' => 2, 'source_page' => 86],
        ['code' => '035', 'name' => 'ENGINEERING SCIENCE', 'category' => 'SCIENCE', 'subject_group_label' => 'Natural Sciences', 'written_papers' => 1, 'source_page' => 92],
        ['code' => '036', 'name' => 'INFORMATION AND COMPUTER STUDIES', 'category' => 'SCIENCE', 'subject_group_label' => 'Natural Sciences', 'written_papers' => 2, 'source_page' => 96],
        ['code' => '041', 'name' => 'BASIC MATHEMATICS', 'category' => 'SCIENCE', 'subject_group_label' => 'Core Subjects', 'written_papers' => 1, 'source_page' => 102],
        ['code' => '042', 'name' => 'ADDITIONAL MATHEMATICS', 'category' => 'SCIENCE', 'subject_group_label' => 'Natural Sciences', 'written_papers' => 1, 'source_page' => 106],
        ['code' => '051', 'name' => 'FOOD AND HUMAN NUTRITION', 'category' => 'BUSINESS', 'subject_group_label' => 'Home Economic Subjects', 'written_papers' => 2, 'source_page' => 109],
        ['code' => '052', 'name' => 'TEXTILES AND GARMENT CONSTRUCTION', 'category' => 'BUSINESS', 'subject_group_label' => 'Home Economic Subjects', 'written_papers' => 2, 'source_page' => 115],
        ['code' => '061', 'name' => 'COMMERCE', 'category' => 'BUSINESS', 'subject_group_label' => 'Business Subjects', 'written_papers' => 1, 'source_page' => 121],
        ['code' => '062', 'name' => 'BOOK KEEPING', 'category' => 'BUSINESS', 'subject_group_label' => 'Business Subjects', 'written_papers' => 1, 'source_page' => 124],
        ['code' => '071', 'name' => 'BUILDING CONSTRUCTION', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 128],
        ['code' => '072', 'name' => 'ARCHITECTURAL DRAUGHTING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 132],
        ['code' => '073', 'name' => 'CIVIL ENGINEERING SURVEYING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 136],
        ['code' => '074', 'name' => 'WOOD AND PAINTING ENGINEERING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 140],
        ['code' => '080', 'name' => 'ELECTRICAL ENGINEERING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 144],
        ['code' => '081', 'name' => 'ELECTRONICS AND COMMUNICATION ENGINEERING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 147],
        ['code' => '082', 'name' => 'ELECTRICAL DRAUGHTING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 151],
        ['code' => '083', 'name' => 'ELECTRONICS DRAUGHTING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 154],
        ['code' => '087', 'name' => 'AUTOMOTIVE ENGINEERING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 157],
        ['code' => '088', 'name' => 'MANUFACTURING ENGINEERING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 161],
        ['code' => '091', 'name' => 'ENGINEERING DRAWING', 'category' => 'BUSINESS', 'subject_group_label' => 'Technical Subjects', 'written_papers' => 1, 'source_page' => 164],
    ],
];
