<?php

return [
    'formats_pdf_path' => env('FTNA_FORMATS_PDF_PATH', base_path('FTNA_FORMATS_VOCATIONAL_STREAM_2025.pdf')),
    'formats_pdf_filename' => env('FTNA_FORMATS_PDF_FILENAME', 'ftna_formats_vocational_stream_2025.pdf'),

    'formats_pdf_paths' => [
        'general' => env('FTNA_FORMATS_GENERAL_PDF_PATH', base_path('FTNA_FORMATS_VOCATIONAL_STREAM_2025.pdf')),
        'vocational' => env('FTNA_FORMATS_VOCATIONAL_PDF_PATH', base_path('FTNA_FORMATS_VOCATIONAL_STREAM_2025.pdf')),
    ],

    'official_links' => [
        'results_directory' => 'https://www.necta.go.tz/results/view/ftna',
        'publications' => 'https://www.necta.go.tz/publications/all',
    ],

    'exam_types' => [
        'FTNA' => 'Form Two National Assessment'
    ],

    'official_subjects_general_2022' => [
        ['code' => '011', 'name' => 'CIVICS', 'source_page' => 1],
        ['code' => '012', 'name' => 'HISTORY', 'source_page' => 4],
        ['code' => '013', 'name' => 'GEOGRAPHY', 'source_page' => 7],
        ['code' => '014', 'name' => 'BIBLE KNOWLEDGE', 'source_page' => 10],
        ['code' => '015', 'name' => 'ELIMU YA DINI YA KIISLAMU', 'source_page' => 13],
        ['code' => '016', 'name' => 'FINE ART', 'source_page' => 17],
        ['code' => '017', 'name' => 'MUSIC', 'source_page' => 20],
        ['code' => '018', 'name' => 'PHYSICAL EDUCATION', 'source_page' => 22],
        ['code' => '019', 'name' => 'THEATRE ARTS', 'source_page' => 25],
        ['code' => '021', 'name' => 'KISWAHILI', 'source_page' => 28],
        ['code' => '022', 'name' => 'ENGLISH LANGUAGE', 'source_page' => 31],
        ['code' => '023', 'name' => 'FRENCH LANGUAGE', 'source_page' => 34],
        ['code' => '025', 'name' => 'ARABIC LANGUAGE', 'source_page' => 37],
        ['code' => '026', 'name' => 'CHINESE LANGUAGE', 'source_page' => 40],
        ['code' => '031', 'name' => 'PHYSICS', 'source_page' => 43],
        ['code' => '032', 'name' => 'CHEMISTRY', 'source_page' => 46],
        ['code' => '033', 'name' => 'BIOLOGY', 'source_page' => 49],
        ['code' => '034', 'name' => 'AGRICULTURE', 'source_page' => 52],
        ['code' => '035', 'name' => 'ENGINEERING SCIENCE', 'source_page' => 55],
        ['code' => '036', 'name' => 'INFORMATION AND COMPUTER STUDIES', 'source_page' => 58],
        ['code' => '041', 'name' => 'BASIC MATHEMATICS', 'source_page' => 61],
        ['code' => '042', 'name' => 'ADDITIONAL MATHEMATICS', 'source_page' => 64],
        ['code' => '050', 'name' => 'HOME ECONOMICS', 'source_page' => 67],
        ['code' => '061', 'name' => 'COMMERCE', 'source_page' => 70],
        ['code' => '062', 'name' => 'BOOK KEEPING', 'source_page' => 73],
        ['code' => '071', 'name' => 'BUILDING CONSTRUCTION', 'source_page' => 76],
        ['code' => '072', 'name' => 'ARCHITECTURAL DRAUGHTING', 'source_page' => 79],
        ['code' => '073', 'name' => 'CIVIL ENGINEERING SURVEYING', 'source_page' => 83],
        ['code' => '074', 'name' => 'WOODWORK AND PAINTING ENGINEERING', 'source_page' => 86],
        ['code' => '080', 'name' => 'ELECTRICAL ENGINEERING', 'source_page' => 90],
        ['code' => '081', 'name' => 'ELECTRONICS AND COMMUNICATION ENGINEERING', 'source_page' => 93],
        ['code' => '090', 'name' => 'MECHANICAL ENGINEERING', 'source_page' => 96],
        ['code' => '091', 'name' => 'ENGINEERING DRAWING', 'source_page' => 99],
    ],

    'official_subjects' => [
        ['code' => '022', 'name' => 'ENGLISH LANGUAGE', 'source_page' => 1],
        ['code' => '023', 'name' => 'FRENCH LANGUAGE', 'source_page' => 6],
        ['code' => '025', 'name' => 'ARABIC LANGUAGE', 'source_page' => 10],
        ['code' => '026', 'name' => 'CHINESE LANGUAGE', 'source_page' => 14],
        ['code' => '033', 'name' => 'BIOLOGY', 'source_page' => 18],
        ['code' => '034', 'name' => 'AGRICULTURE', 'source_page' => 21],
        ['code' => '035', 'name' => 'ENGINEERING SCIENCE', 'source_page' => 24],
        ['code' => '043', 'name' => 'MATHEMATICS', 'source_page' => 30],
        ['code' => '060', 'name' => 'HISTORIA YA TANZANIA NA MAADILI', 'source_page' => 34],
        ['code' => '065', 'name' => 'BUSINESS STUDIES', 'source_page' => 39],
        ['code' => '201', 'name' => 'HANDLOOM WEAVING', 'source_page' => 43],
        ['code' => '204', 'name' => 'DESIGN, SEWING AND CLOTH TECHNOLOGY', 'source_page' => 50],
        ['code' => '205', 'name' => 'LEATHER GOODS AND FOOTWEAR', 'source_page' => 58],
        ['code' => '241', 'name' => 'FOOTBALL PERFORMANCE', 'source_page' => 67],
        ['code' => '242', 'name' => 'NETBALL PERFORMANCE', 'source_page' => 75],
        ['code' => '243', 'name' => 'TRACK EVENTS PERFORMANCE', 'source_page' => 81],
        ['code' => '396', 'name' => 'LIFE SKILLS', 'source_page' => 88],
        ['code' => '397', 'name' => 'TECHNICAL DRAWING', 'source_page' => 95],
        ['code' => '398', 'name' => 'COMPUTER APPLICATION', 'source_page' => 99],
        ['code' => '403', 'name' => 'ANIMAL HEALTH AND PRODUCTION', 'source_page' => 105],
        ['code' => '404', 'name' => 'HORTICULTURAL PRODUCTION', 'source_page' => 112],
        ['code' => '405', 'name' => 'FIELD CROP PRODUCTION', 'source_page' => 122],
        ['code' => '406', 'name' => 'WOOD PROCESSING', 'source_page' => 130],
        ['code' => '412', 'name' => 'TOURISM', 'source_page' => 137],
        ['code' => '463', 'name' => 'FOOD PRODUCTION', 'source_page' => 140],
        ['code' => '464', 'name' => 'FOOD AND BEVERAGE SERVICES AND SALES', 'source_page' => 151],
        ['code' => '481', 'name' => 'ACTING', 'source_page' => 160],
        ['code' => '485', 'name' => 'MUSIC PERFORMANCE', 'source_page' => 166],
        ['code' => '487', 'name' => 'DRAWING AND PAINTING', 'source_page' => 174],
        ['code' => '801', 'name' => 'MASONRY AND BRICKLAYING', 'source_page' => 177],
        ['code' => '804', 'name' => 'CARPENTRY AND JOINERY WITH METAL WORKS', 'source_page' => 184],
        ['code' => '805', 'name' => 'PLUMBING AND PIPE FITTING', 'source_page' => 192],
        ['code' => '806', 'name' => 'PAINTING AND SIGN WRITING', 'source_page' => 203],
        ['code' => '824', 'name' => 'ELECTRICAL INSTALLATION', 'source_page' => 212],
        ['code' => '827', 'name' => 'SOLAR POWER INSTALLATION', 'source_page' => 223],
        ['code' => '841', 'name' => 'COMPUTER PROGRAMMING', 'source_page' => 235],
        ['code' => '842', 'name' => 'GRAPHIC DESIGN', 'source_page' => 245],
        ['code' => '843', 'name' => 'ELECTRONICS', 'source_page' => 253],
        ['code' => '861', 'name' => 'MOTOR VEHICLE MECHANICS', 'source_page' => 262],
        ['code' => '862', 'name' => 'AUTO ELECTRICS', 'source_page' => 277],
        ['code' => '881', 'name' => 'WELDING AND METAL FABRICATION', 'source_page' => 292],
        ['code' => '882', 'name' => 'REFRIGERATION AND AIR CONDITIONING', 'source_page' => 301],
    ],
];
